version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=secure_pass_here
      - DB_NAME=postgres
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - app_network

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=secure_pass_here
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
